/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practica_7;

import java.util.List;

import io.javalin.Javalin;
import io.javalin.core.util.RouteOverviewPlugin;
import io.javalin.plugin.openapi.OpenApiOptions;
import io.javalin.plugin.openapi.OpenApiPlugin;
import io.javalin.plugin.openapi.ui.SwaggerOptions;
import io.swagger.v3.oas.models.info.Info;
import kong.unirest.GenericType;
import kong.unirest.HttpResponse;
import kong.unirest.JsonNode;
import kong.unirest.Unirest;
import practica_7.controladores.ApiControlador;
import practica_7.controladores.SoapControlador;
import practica_7.encapsulaciones.Estudiante;
import practica_7.servicios.EstudianteServices;

public class Main {

    public static void main(String[] args) {
        
        //Creando la instancia del servidor.
        Javalin app = Javalin.create(config ->{
            config.registerPlugin(new RouteOverviewPlugin("/rutas")); //aplicando plugins de las rutas
            config.registerPlugin(new OpenApiPlugin(getOpenApiOptions()));
        });

        new ApiControlador(app).aplicarRutas();
        new SoapControlador(app).aplicarRutas();

        app.start();

        // Crear un nuevo estudiante.
        HttpResponse<JsonNode> response = Unirest.post("http://localhost:7000/api/estudiante/")
            .header("Content-Type", "application/json")
            .body("{\"matricula\": 20170639, \"nombre\": \"Louvens\", \"carrera\": \"ISC\"}")
            .asJson();

        // // Crear otro nuevo estudiante.
        HttpResponse<JsonNode> response2 = Unirest.post("http://localhost:7000/api/estudiante/")
            .header("Content-Type", "application/json")
            .body("{\"matricula\": 20170982, \"nombre\": \"Baldera\", \"carrera\": \"ISC\"}")
            .asJson();
        
        System.out.println("\nListar estudiantes creados:");
        for (Estudiante e : EstudianteServices.getInstancia().listarEstudiante()) {
            System.out.println(e.getMatricula() + " " + e.getNombre() + " " + e.getCarrera());
        }

        // // Consultar un estudiante.
        System.out.println("\nConsultar estudiante con matrícula 20170639:");
        Estudiante estudiante = Unirest.get("http://localhost:7000/api/estudiante/{id}")
            .routeParam("id", "20170639")
            .asObject(Estudiante.class)
            .getBody();
        System.out.println(estudiante.getMatricula() + " " + estudiante.getNombre() + " " + estudiante.getCarrera());
        
        // Borrar un estudiante.
        System.out.println("\nEstudiante con matrícula 20170639 borrado");
        HttpResponse borrarEstudiante = Unirest.delete("http://localhost:7000/api/estudiante/{matricula}")
            .routeParam("matricula", "20170639")
            .asEmpty();

        // Listar Todos los estudiantes.
        List<Estudiante> estudiantes = Unirest.get("http://localhost:7000/api/estudiante/")
        .asObject(new GenericType<List<Estudiante>>(){})
        .getBody();

        System.out.println("\nListar estudiantes creados:");
        for (Estudiante e : estudiantes) {
            System.out.println(e.getMatricula() + " " + e.getNombre() + " " + e.getCarrera());
        }
        
    }

    private static OpenApiOptions getOpenApiOptions() {
        Info applicationInfo = new Info()
                .version("1.0")
                .description("My Application");
        return new OpenApiOptions(applicationInfo).path("/openapi").swagger(new SwaggerOptions("/openapi-ui"));
    }
}
